# Generated by Django 5.2.14 on 2026-05-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Категорія"
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "Категорія блогу",
                "verbose_name_plural": "Категорії блогу",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "date_label",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Дата (текст)"
                    ),
                ),
                ("excerpt", models.TextField(verbose_name="Короткий опис")),
                ("content", models.TextField(blank=True, verbose_name="Повний текст")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL зображення"
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="blog/")),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="blog.blogcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стаття",
                "verbose_name_plural": "Статті",
                "ordering": ("-legacy_id",),
            },
        ),
    ]
