# Generated by Django 5.2.14 on 2026-05-19 16:20

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Повний текст"
            ),
        ),
    ]
