# Generated by Django 5.2.14 on 2026-05-19 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=32, unique=True, verbose_name="Код"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("percent", "Відсоток"), ("fixed", "Фіксована сума")],
                        default="percent",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Значення"
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=64, verbose_name="Підпис"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Активний")),
                (
                    "min_order",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Мін. замовлення",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="Діє до"),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоди",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Нове"),
                            ("processing", "В обробці"),
                            ("shipped", "Відправлено"),
                            ("delivered", "Доставлено"),
                            ("cancelled", "Скасовано"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("first_name", models.CharField(max_length=80, verbose_name="Ім'я")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Прізвище"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "delivery",
                    models.CharField(
                        choices=[
                            ("pickup", "Самовивіз"),
                            ("nova", "Нова Пошта"),
                            ("courier", "Кур'єр Київ"),
                            ("truck", "Вантажне авто"),
                        ],
                        default="nova",
                        max_length=16,
                        verbose_name="Доставка",
                    ),
                ),
                (
                    "delivery_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Адреса доставки"
                    ),
                ),
                (
                    "delivery_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Вартість доставки",
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        choices=[
                            ("cash", "Готівка"),
                            ("card", "Картка"),
                            ("invoice", "Безготівковий"),
                        ],
                        default="card",
                        max_length=16,
                        verbose_name="Оплата",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Знижка",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Сума товарів",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Разом"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Коментар")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.promocode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиція замовлення",
                "verbose_name_plural": "Позиції замовлення",
            },
        ),
    ]
