# Generated by Django 5.2.14 on 2026-05-19 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Кількість"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("defect", "Брак / пошкодження"),
                            ("wrong", "Не відповідає опису"),
                            ("size", "Не підійшов розмір/тип"),
                            ("changed_mind", "Передумав"),
                            ("other", "Інше"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Причина",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Коментар клієнта"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На розгляді"),
                            ("approved", "Прийнято"),
                            ("rejected", "Відхилено"),
                            ("refunded", "Повернено"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="Примітка адміна"),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Сума повернення",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Опрацьовано"
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="orders.orderitem",
                        verbose_name="Позиція замовлення",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Запит на повернення",
                "verbose_name_plural": "Запити на повернення",
                "ordering": ("-created_at",),
            },
        ),
    ]
