# Generated by Django 5.2.14 on 2026-05-19 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=120, verbose_name="Назва")),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренди",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=120, verbose_name="Назва")),
            ],
            options={
                "verbose_name": "Категорія",
                "verbose_name_plural": "Категорії",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=120, verbose_name="Назва")),
            ],
            options={
                "verbose_name": "Тип товару",
                "verbose_name_plural": "Типи товарів",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        db_index=True,
                        max_length=10,
                        unique=True,
                        verbose_name="Legacy ID (з js.js)",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва")),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ціна"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Стара ціна",
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("small", "Малий"),
                            ("medium", "Середній"),
                            ("large", "Великий"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Фасування",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="Залишок"),
                ),
                ("promo", models.BooleanField(default=False, verbose_name="Акція")),
                ("popular", models.BooleanField(default=False, verbose_name="Хіт")),
                ("is_new", models.BooleanField(default=False, verbose_name="Новинка")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL зображення"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Файл зображення",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Опис")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.producttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товари",
                "ordering": ("legacy_id",),
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(default=5, verbose_name="Оцінка"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Коментар")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Відгук",
                "verbose_name_plural": "Відгуки",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_type"], name="catalog_pro_product_c95501_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="catalog_pro_brand_i_69e6f6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["promo"], name="catalog_pro_promo_0c0c84_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["popular"], name="catalog_pro_popular_7b0664_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_new"], name="catalog_pro_is_new_087fb1_idx"),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("product", "user"), name="unique_review_per_user_product"
            ),
        ),
    ]
