# Generated by Django 5.2.14 on 2026-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="partner_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ціна для клієнтів з tier=partner. Якщо не вказана — діє оптова, потім роздрібна.",
                max_digits=10,
                null=True,
                verbose_name="Партнерська ціна",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="wholesale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ціна для клієнтів з tier=wholesale. Якщо не вказана — діє роздрібна.",
                max_digits=10,
                null=True,
                verbose_name="Оптова ціна",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Роздрібна ціна"
            ),
        ),
    ]
