# Generated by Django 5.2.14 on 2026-05-19 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Назва компанії"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Примітки адміна"),
        ),
        migrations.AddField(
            model_name="user",
            name="tax_id",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="ЄДРПОУ/ІПН"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tier",
            field=models.CharField(
                choices=[
                    ("regular", "Звичайний"),
                    ("wholesale", "Оптовий"),
                    ("partner", "Партнер"),
                ],
                default="regular",
                help_text="Звичайний — роздрібні ціни; Оптовий — оптові ціни; Партнер — партнерські ціни.",
                max_length=16,
                verbose_name="Категорія клієнта",
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="Доставка",
                        help_text="Напр. «Дім», «Офіс»",
                        max_length=60,
                        verbose_name="Назва",
                    ),
                ),
                ("city", models.CharField(max_length=80, verbose_name="Місто")),
                (
                    "street",
                    models.CharField(max_length=200, verbose_name="Вулиця та номер"),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Квартира/офіс"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=10, verbose_name="Індекс"),
                ),
                (
                    "np_warehouse",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Відділення НП"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="За замовчуванням"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Адреса",
                "verbose_name_plural": "Адреси",
                "ordering": ("-is_default", "-created_at"),
            },
        ),
    ]
