# Generated by Django 5.2.14 on 2026-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Ім'я")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="Тема"),
                ),
                ("message", models.TextField(verbose_name="Повідомлення")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("contact", "Сторінка контактів"),
                            ("footer", "Футер"),
                            ("business", "Для бізнесу"),
                            ("other", "Інше"),
                        ],
                        default="contact",
                        max_length=16,
                        verbose_name="Джерело",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Нова"),
                            ("in_progress", "В обробці"),
                            ("resolved", "Опрацьовано"),
                        ],
                        default="new",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Опрацьовано"
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="Примітка адміна"),
                ),
            ],
            options={
                "verbose_name": "Контактна заявка",
                "verbose_name_plural": "Контактні заявки",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "confirmed",
                    models.BooleanField(default=False, verbose_name="Підтверджена"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Підписався"),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Відписався"
                    ),
                ),
            ],
            options={
                "verbose_name": "Підписка на розсилку",
                "verbose_name_plural": "Підписки на розсилку",
                "ordering": ("-created_at",),
            },
        ),
    ]
